#!/bin/sh

################################################################################
#
# Download and install Robo tip in Termux context.
#
################################################################################

pkg install git --yes
pkg install openssh --yes
pkg install php --yes
pkg install sqlite --yes
pkg install termux-services --yes
pkg install wget --yes

# Download composer, as per instructions from https://getcomposer.org/download/
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

# Move globally.
chmod +x composer.phar && mv composer.phar $PREFIX/bin/composer

# Install Robo globally.
wget http://robo.li/robo.phar
chmod +x robo.phar && mv robo.phar $PREFIX/bin/robo

# Clone repo
cd ~
git clone https://github.com/Gizra/tip-starter.git
cd tip-starter
composer install

cd ~
git clone https://github.com/Gizra/mdr-symfony.git
cd mdr-symfony/app
composer install
# Prepare DB.
php bin/console doctrine:migrations:migrate -n

# Setup mdr --daemon service script
mkdir -p $PREFIX/var/service/tipd/log
cd $PREFIX/var/service
echo '#!/bin/sh' > tipd/run
echo 'cd ~/tip-starter && php -S localhost:1234 -t public -c custom-php.ini 2>&1' >> tipd/run
chmod +x tipd/run
touch tipd/down
ln -sf $PREFIX/share/termux-services/svlogger tipd/log/run

# Setup mdr --daemon service script
mkdir -p $PREFIX/var/service/mdrd/log
cd $PREFIX/var/service
echo '#!/bin/sh' > mdrd/run
echo 'cd ~/mdr-symfony/app && php -S localhost:8080 -t public -c custom-php.ini 2>&1' >> mdrd/run
chmod +x mdrd/run
touch mdrd/down
ln -sf $PREFIX/share/termux-services/svlogger mdrd/log/run

# symlink `tip` executable to HOME directory.
cd ~
ln -s tip-starter/tip .


