#!/bin/bash

################################################################################
#
# Download and install Robo tip in Termux context.
#
################################################################################

pkg install git
pkg install php
pkg install sqlite

# Download composer, as per instructions from https://getcomposer.org/download/
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

# Clone repo
git clone git@github.com:Gizra/tip-starter.git
# symlink `tip` executable to HOME directory.
ln -s tip-starter/tip .

