#!/bin/sh

################################################################################
#
# Download and install Robo tip in Termux context.
#
################################################################################

pkg install git
pkg install php
pkg install sqlite
pkg install termux-services

# Download composer, as per instructions from https://getcomposer.org/download/
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

# Move globally.
chmod +x composer.phar && mv composer.phar $PREFIX/bin/composer

# Clone repo
git clone git@github.com:Gizra/tip-starter.git
cd tip-starter/app
composer install
cd ~

git clone git@github.com:Gizra/mdr-symfony.git
cd mdr-symfony/app
composer install
cd ~

# symlink `tip` executable to HOME directory.
ln -s tip-starter/tip .

# Setup mdr --daemon service script
mkdir -p $PREFIX/var/service/mdr/log
cd $PREFIX/var/service
echo '#!/bin/sh' > mdr/run
echo 'php -S localhost:8080 -t ~/mdr-git/app/public -c ~/mdr-git/app/custom-php.ini 2>&1' >> mdr/run
chmod +x mdr/run
touch mdr/down
ln -sf $PREFIX/share/termux-services/svlogger mdr/log/run

